In [1]:
import numpy as np

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

#Sample film reviews and labels (1 = Positive, 0 = Negative)
reviews = [
    "I loved this movie",
    "The film was fantastic",
    "It was a wonderful experience",
    "Amazing movie and great acting",
    "Absolutely loved the storyline",
    "It was okay, not great",
    "I hated this movie",
    "It was a terrible film",
    "The movie was boring and slow",
    "Worst acting and bad plot"
]
labels = [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]

In [2]:
reviews

['I loved this movie',
 'The film was fantastic',
 'It was a wonderful experience',
 'Amazing movie and great acting',
 'Absolutely loved the storyline',
 'It was okay, not great',
 'I hated this movie',
 'It was a terrible film',
 'The movie was boring and slow',
 'Worst acting and bad plot']

In [3]:
#tokenize the text
tokenizer = Tokenizer(num_words=1000, oov_token="<OOV>")
tokenizer.fit_on_texts(reviews)
sequences = tokenizer.texts_to_sequences(reviews)

#pad sequences to equal length
padded_sequences = pad_sequences(sequences, maxlen=6, padding='post')

#convert to NumPy arrays
X = np.array(padded_sequences)
y = np.array(labels)


In [4]:
print(X)

[[ 7  8  9  3  0  0]
 [ 4 10  2 14  0  0]
 [ 5  2 11 15 16  0]
 [17  3  6 12 13  0]
 [18  8  4 19  0  0]
 [ 5  2 20 21 12  0]
 [ 7 22  9  3  0  0]
 [ 5  2 11 23 10  0]
 [ 4  3  2 24  6 25]
 [26 13  6 27 28  0]]


In [5]:
#build RNN model
model = Sequential()
model.add(Embedding(input_dim=1000, output_dim=16, input_length=6))
model.add(SimpleRNN(16))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

#train
model.fit(X, y, epochs=100, verbose=1)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.6000 - loss: 0.6742
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7000 - loss: 0.6665
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7000 - loss: 0.6589
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8000 - loss: 0.6511
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8000 - loss: 0.6433
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9000 - loss: 0.6354
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9000 - loss: 0.6274
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9000 - loss: 0.6192
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9000 - loss: 0.6109
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 1.0000 - loss: 0.6024
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 1.0000 - loss: 0.5937
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - los

In [6]:
#predict sentiment on new review
test_review = ["The movie was great"]
test_seq = tokenizer.texts_to_sequences(test_review)
test_pad = pad_sequences(test_seq, maxlen=6, padding='post')

pred = model.predict(test_pad)
sentiment = "Positive" if pred[0][0] > 0.5 else "Negative"

print("Review:", test_review[0])
print("Predicted Sentiment:", sentiment)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step
Review: The movie was great
Predicted Sentiment: Positive
